# Generated by Django 3.2.4 on 2021-07-05 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Progress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('task', models.EmailField(max_length=200)),
                ('report', models.CharField(max_length=100)),
                ('date', models.DateField()),
            ],
        ),
    ]
